from enum import StrEnum


class UserRole(StrEnum):
    ADMIN = "ADMIN"
    GENERAL_COORDINATOR = "GENERAL_COORDINATOR"
    COORDINATOR = "COORDINATOR"
    LINK = "LINK"
    FRIEND = "FRIEND"


class PersonRole(StrEnum):
    """Final hierarchy roles. AMIGO is deliberately not an auth role."""

    ADMIN = "ADMIN"
    COORDINADOR_GENERAL = "COORDINADOR_GENERAL"
    COORDINADOR = "COORDINADOR"
    ENLACE = "ENLACE"
    AMIGO = "AMIGO"


AUTHENTICABLE_PERSON_ROLES = frozenset(
    {
        PersonRole.ADMIN,
        PersonRole.COORDINADOR_GENERAL,
        PersonRole.COORDINADOR,
        PersonRole.ENLACE,
    }
)


class EventStatus(StrEnum):
    BORRADOR = "BORRADOR"
    PUBLICADO = "PUBLICADO"
    EN_CURSO = "EN_CURSO"
    FINALIZADO = "FINALIZADO"
    CANCELADO = "CANCELADO"


# Allowed forward transitions per status.
# Despublicar (PUBLICADO → BORRADOR) returns the event to editable draft state.
EVENT_TRANSITIONS: dict["EventStatus", frozenset["EventStatus"]] = {
    EventStatus.BORRADOR: frozenset({EventStatus.PUBLICADO, EventStatus.CANCELADO}),
    EventStatus.PUBLICADO: frozenset(
        {EventStatus.BORRADOR, EventStatus.EN_CURSO, EventStatus.CANCELADO}
    ),
    EventStatus.EN_CURSO: frozenset({EventStatus.FINALIZADO, EventStatus.CANCELADO}),
    EventStatus.FINALIZADO: frozenset(),
    EventStatus.CANCELADO: frozenset(),
}


class InvitationStatus(StrEnum):
    PENDIENTE = "PENDIENTE"
    ACEPTADA = "ACEPTADA"
    RECHAZADA = "RECHAZADA"
    CANCELADA = "CANCELADA"
    EXPIRADA = "EXPIRADA"


class AttendanceStatus(StrEnum):
    INVITADO = "INVITADO"
    CONFIRMADO = "CONFIRMADO"
    PRESENTE = "PRESENTE"
    AUSENTE = "AUSENTE"
    CANCELADO = "CANCELADO"


class CheckinMethod(StrEnum):
    QR = "QR"
    MANUAL = "MANUAL"
    GEOLOCALIZACION = "GEOLOCALIZACION"
    CODIGO = "CODIGO"
    ADMIN = "ADMIN"


class EstatusPersona(StrEnum):
    ACTIVO = "ACTIVO"
    INACTIVO = "INACTIVO"
    BAJA = "BAJA"


class DocumentoTipo(StrEnum):
    CV = "CV"
    FOTO = "FOTO"
    IDENTIFICACION = "IDENTIFICACION"
    OTRO = "OTRO"


class TipoGeocerca(StrEnum):
    ESTADO = "ESTADO"
    MUNICIPIO = "MUNICIPIO"
    DISTRITO = "DISTRITO"  # Deprecated: do not import new data; use DISTRITO_LOCAL/DISTRITO_FEDERAL.
    SECCION = "SECCION"
    DISTRITO_LOCAL = "DISTRITO_LOCAL"
    DISTRITO_FEDERAL = "DISTRITO_FEDERAL"


class NecesidadComunidad(StrEnum):
    INSEGURIDAD = "INSEGURIDAD"
    FALTA_ALUMBRADO_PUBLICO = "FALTA_ALUMBRADO_PUBLICO"
    CALLES_MAL_ESTADO = "CALLES_MAL_ESTADO"
    FALTA_AGUA_POTABLE = "FALTA_AGUA_POTABLE"
    PROBLEMAS_DRENAJE = "PROBLEMAS_DRENAJE"
    RECOLECCION_BASURA_DEFICIENTE = "RECOLECCION_BASURA_DEFICIENTE"
    FALTA_LIMPIEZA = "FALTA_LIMPIEZA"
    FALTA_TRANSPORTE_PUBLICO = "FALTA_TRANSPORTE_PUBLICO"
    FALTA_PARQUES_ESPACIOS_RECREATIVOS = "FALTA_PARQUES_ESPACIOS_RECREATIVOS"
    VENTA_CONSUMO_DROGAS = "VENTA_CONSUMO_DROGAS"
    FALTA_ATENCION_MEDICA_CERCANA = "FALTA_ATENCION_MEDICA_CERCANA"
    FALTA_APOYOS_SOCIALES = "FALTA_APOYOS_SOCIALES"
    FALTA_EMPLEO = "FALTA_EMPLEO"
    FALTA_ATENCION_ADULTOS_MAYORES = "FALTA_ATENCION_ADULTOS_MAYORES"
    FALTA_ATENCION_JOVENES = "FALTA_ATENCION_JOVENES"


MAX_NECESIDADES_COMUNIDAD_POR_PERSONA = 3
